# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LanguageModelFeaturizer"
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: true

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
